services:
  newspaper:
    build: .
    volumes:
      - ./parser/session_maxim.session:/app/parser/session_maxim.session
    command: >
      bash -c "
      cd parser &&
      python3 parse_channels.py &&
      cd ../ &&
      cd scripts &&
      node generate-html.js && 
      cd ../ &&\
      prince -s generated/style/style.css -s generated/style/fonts.css generated/output.html -o generated/output.pdf && \
      cd sender &&
      node send.js"